### ISSUE TITLE
Скласти інтро

### ISSUE THREAD

**Issue by LiubovChernohor** [LiubovChernohor/homepage#4]
Скласти інтро (вступ), де в 2-4 реченнях описати, що замовник робить, що подобається робити, що хочеться робити краще, що важливо робити, тощо.

**Comment by Andrey7315** [comment]
I'm sure, all of you know me as the best president in the world, as a rich, powerful, and risky person.  And it was not I who lost the elections in 2020, it was you who lost, America lost, and the whole world too, because I'm the best of the best! I'm the smartest, the most farsighted, and the most successful one which America's ever had. And, remember, I'll be back!!!

**Comment by LiubovChernohor** [comment]
Super! Thaaaanks!
